.\"                                      Hey, EMACS: -*- nroff -*-
.\" First parameter, NAME, should be all caps
.\" Second parameter, SECTION, should be 1-8, maybe w/ subsection
.\" other parameters are allowed: see man(7), man(1)
.TH SIMPLE-SCAN 1 "December 21, 2009"
.\" Please adjust this date whenever revising the manpage.
.\"
.\" Some roff macros, for reference:
.\" .nh        disable hyphenation
.\" .hy        enable hyphenation
.\" .ad l      left justify
.\" .ad b      justify to both left and right margins
.\" .nf        disable filling
.\" .fi        enable filling
.\" .br        insert line break
.\" .sp <n>    insert n+1 empty lines
.\" for manpage-specific macros, see man(7)
.SH NAME
simple-scan \- Scanning utility
.SH SYNOPSIS
.BI "simple-scan [" DEVICE "]"
.SH DESCRIPTION
This manual page documents briefly the
.B simple-scan
command.
.PP
.\" TeX users may be more comfortable with the \fB<whatever>\fP and
.\" \fI<whatever>\fP escape sequences to invode bold face and italics,
.\" respectively.
.B Document Scanner
is an easy-to-use application, designed to let users connect their
scanner and quickly have the image/document in an appropriate format.
.PP
.B Document Scanner
has been written with GTK+ libraries, and after installing the
application you can run it from the
.B Applications
menu.
.SH OPTIONS
These programs follow the usual GNU command line syntax, with long
options starting with two dashes (`-').
A summary of options is included below.
For a complete description, see the Info files.
.TP
.B \-d, \-\-debug
Print debugging messages.
.TP
.B \-v, \-\-version
Show release version.
.TP
.B \-?, \-\-help
Show help options.
.TP
.B \-\-help-all
Show all help options.
.TP
.B \-d, \-\-help-gtk
Show GTK+ options.
.SH AUTHOR
simple-scan was written by Robert Ancell <robert.ancell@canonical.com>.
.PP
This manual page was written by Alessio Treglia <quadrispro@ubuntu.com>,
for the Debian project (and may be used by others).
