name: simple-scan
version: git
summary: Document Scanning Application
description: |
  Simple Scan allows you to get images from a scanner (e.g. a flatbed scanner)

grade: stable # must be 'stable' to release into candidate/stable channels
confinement: strict

plugs:
  gnome-3-26-1604:
    interface: content
    target: $SNAP/gnome-platform
    default-provider: gnome-3-26-1604
  gtk-3-themes:
    interface: content
    target: $SNAP/data-dir/themes
    default-provider: gtk-common-themes
  icon-themes:
    interface: content
    target: $SNAP/data-dir/icons
    default-provider: gtk-common-themes
  sound-themes:
    interface: content
    target: $SNAP/data-dir/sounds
    default-provider: gtk-common-themes

slots:
  # for GtkApplication registration
  simple-scan:
    interface: dbus
    bus: session
    name: org.gnome.SimpleScan
 
apps:
  simple-scan:
    plugs:
      - desktop
      - desktop-legacy
      - network
      - network-control
      - home
      - gsettings
      - hardware-observe
      - mount-observe
      - system-observe
      - io-ports-control
      - raw-usb
      - unity7
    command: bin/desktop-launch ${SNAP}/usr/bin/simple-scan
    desktop: usr/share/applications/simple-scan.desktop
    environment:
      GSETTINGS_SCHEMA_DIR: $SNAP/share/glib-2.0/schemas

parts:
  libsane:
    after: [desktop-gnome-platform]
    source: https://salsa.debian.org/debian/sane-backends.git
    source-type: git
    source-tag: upstream/1.0.27
    plugin: autotools
    configflags: [--prefix=/snap/simple-scan/current/usr, --with-api-spec=no]
    organize:
      snap/simple-scan/current/usr: usr
    build-attributes: ['no-system-libraries']
    build-packages:
      - autotools-dev
      - autoconf
      - chrpath
      - dh-systemd
      - gettext
      - libavahi-client-dev
      - libcups2-dev
      - libgphoto2-dev
      - libieee1284-3-dev
      - libjpeg-dev
      - libltdl3-dev
      - libsystemd-dev
      - libtiff-dev
      - libusb-1.0-0-dev
      - pkg-config
      - po-debconf
      - xutils-dev

  simple-scan:
    after: [libsane]
    source: .
    source-type: git
    #source-tag: 3.30.0
    plugin: meson
    meson-parameters: [--prefix=/usr]
    organize:
      snap/simple-scan/current/usr: usr
    build-attributes: ['no-system-libraries']
    build-packages:
      - desktop-file-utils
      - gettext
      - gnome-common
      - intltool
      - itstool
      - libcairo2-dev
      - libcolord-dev
      - libdbus-glib-1-dev
      - libglib2.0-dev
      - libgtk-3-dev
      - libgdk-pixbuf2.0-dev
      - libgusb-dev
      - libpackagekit-glib2-dev
      - libsane-dev
      - python-scour
      - valac
      - zlib1g-dev
  libs:
    plugin: nil
    stage-packages:
      - libgusb2
      - libpackagekit-glib2-18
      - libieee1284-3
